### ISSUE TITLE
Cant get LuckPerms and ChatPrefixer to work.

### ISSUE THREAD

**Issue by Chain-BC** [Caelum100/ChatPrefixer#2]
I tried using the default prefixes and the placeholder api prefixes but it didn't work :( please help me

**Comment by caelunshun** [comment]
Sorry for seeing this way too late. I appreciate that you asked for help here rather than in the plugin review section.

In the future, please provide more detail when asking for help—"it didn't work" doesn't tell me much. Were there any errors in the console? What was your configuration? What result did you expect, and what actually happened?

These questions are essential to being able to help you or fix any bugs.

For now, I will close this issue, as it doesn't seem to be an issue with the plugin.
